### ISSUE TITLE
decrypt image

### ISSUE THREAD

**Issue by contatodct** [open-wa/wa-decrypt-nodejs#46]
I am a beginner in nodejs and I am not able to decrypt image ....

could you please show me a basic example?

because when I run the example available I have the following error

root@167:/var/www/adm/services# node ../../admin/teste.js
/var/www/admin/teste.js:1
import { decryptMedia } from '@open-wa/wa-decrypt';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
root@167:/var/www/adm/services#
==========================================
this and the script I'm using...

import { decryptMedia } from '@open-wa/wa-decrypt';
const mime = require('mime-types');
const fs = require('fs');

const processMessage = async message => {
    if (message.mimetype) {
      const filename = `${message.t}.${mime.extension(message.mimetype)}`;
      const mediaData = await decryptMedia(message);
      const imageBase64 = `data:${message.mimetype};base64,${mediaData.toString(
        'base64'
      )}`;
      fs.writeFile(filename, mediaData, function(err) {
        if (err) {
          return console.log(err);
        }
        console.log('The file was saved!');
      });
    }
  }
==========================================
I would just like to save the received images ...

please help me

**Comment by kauly** [comment]
Seem's to me that you are not using typescript, Try use requir insteat of import:

```
const { decryptMedia } = require('@open-wa/wa-decrypt)';
```

**Comment by contatodct** [comment]
const { decryptMedia } = require('@open-wa/wa-decrypt');
const mime = require('mime-types');
const fs = require('fs');
const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));

function start(client) {
  client.onMessage(message => {
    if (message.mimetype) {
      const filename = `${message.t}.${mime.extension(message.mimetype)}`;
      const mediaData =  await decryptMedia(message);
      const imageBase64 = `data:${message.mimetype};base64,${mediaData.toString('base64')}`;

      fs.writeFile(filename, mediaData, function(err) {
        if (err) {
          return console.log(err);
        }
        console.log('The file was saved!');
      });
      client.sendText(message.from, '👋 Received OK!');
    }
  });
}
--------------------------------------------------------------
error....
--------------------------------------------------------------
root@167:/var/www/adm/services# node ../../admin/teste.js
/var/www/admin/teste.js:12
      const mediaData =  await decryptMedia(message);
                         ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
root@167:/var/www/adm/services#

**Comment by kauly** [comment]
As the error says, you need to use async. You need to powerup your JS skills man, these errors are not related to this library.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

```
async function start(client) { 
 ....
}
```
